# Generated by Django 3.2.23 on 2023-12-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorydump',
            name='build',
        ),
        migrations.RemoveField(
            model_name='memorydump',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='memorydump',
            name='map',
        ),
        migrations.RemoveField(
            model_name='memorydump',
            name='platform',
        ),
        migrations.AddField(
            model_name='memorydump',
            name='dump_label',
            field=models.CharField(default='Legacy memdump location', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='display',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='build',
            name='stream',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_identifier', models.CharField(max_length=100)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.build')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.configuration')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.map')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.platform')),
            ],
        ),
        migrations.AddField(
            model_name='memorydump',
            name='test_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.testrun'),
            preserve_default=False,
        ),
    ]
