# Generated by Django 3.2.23 on 2023-12-12 10:13

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('display', models.CharField(blank=True, max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_identifier', models.CharField(max_length=100)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.build')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.configuration')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.map')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.platform')),
            ],
        ),
        migrations.CreateModel(
            name='MemoryDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dump_label', models.CharField(max_length=255)),
                ('summary_json', jsonfield.fields.JSONField(default=dict)),
                ('allocations_json', jsonfield.fields.JSONField(default=dict)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telemetry_db.testrun')),
            ],
        ),
    ]
