# Generated by Django 3.2.23 on 2023-12-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_db', '0002_mesh_meshdumplocation_meshinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesh',
            name='dir',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
