# Generated by Django 3.2.23 on 2023-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry_db', '0003_alter_mesh_dir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meshinstance',
            name='cpu_size',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meshinstance',
            name='gpu_size',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meshinstance',
            name='instance_count',
            field=models.IntegerField(db_index=True),
        ),
    ]
